from tkinter import *
from tkinter import messagebox

root = Tk()

some_label = Label(root, text="Hello, world!")
some_label.pack()
question_entry = Entry(root, font=8)
question_entry.place(relheight=0.38, relwidth=0.9, x=31, y=30)
possible_ans_a_label = Label(root, text="A")
possible_ans_a_label.place(x=31, y=240)
possible_ans_b_label = Label(root, text="B")
possible_ans_b_label.place(x=430, y=240)
possible_ans_c_label = Label(root, text="C")
possible_ans_c_label.place(x=31, y=340)
possible_ans_d_label = Label(root, text="D")
possible_ans_d_label.place(x=430, y=340)
possible_ans_a = Entry(root)
possible_ans_b = Entry(root)
possible_ans_b = Entry(root)
possible_ans_c = Entry(root)
possible_ans_d = Entry(root)
possible_ans_a.place(relwidth=0.2, x=50, y=240)
possible_ans_b.place(relwidth=0.2, x=449, y=240)
possible_ans_c.place(relwidth=0.2, x=50, y=340)
possible_ans_d.place(relwidth=0.2, x=449, y=340)
submit_button = Button(root, text="Submit", pady=2)
submit_button.place(x=300, y=475)
root.title('Convert Questions to JSON')
root.maxsize(620, 520)
root.minsize(620, 520)
root.geometry("620x520")
root.mainloop()
